name: Build and Deploy

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install MdBook
        run: cargo install mdbook
      - name: Build the book
        run: mdbook build
      - name: Create .ssh folder
        run: mkdir ~/.ssh
      - name: Save key
        run: echo "${{ secrets.DIGITAL_OCEAN_KEY }}" > ~/.ssh/id_ed25519
      - name: Save known host
        run: echo "${{ secrets.DROPLET_KNOWN_HOST }}" >> ~/.ssh/known_hosts
      - name: fix .ssh permissions
        run: chmod -R 700 ~/.ssh
      - name: Run Deploy Script
        run: ssh -i ~/.ssh/id_ed25519 brooks@137.184.46.223 "bash -e install.sh 2>&1 >> log"
